#include<fstream.h>
#include<conio.h>
#include<stdio.h>
class antique
{
private:
int ano;
char aname;
float price;
public:
void buy()
{
cout<<"enter ano";
cin>>ano;
cout<<"enter aname";
gets(aname);
cout<<"enter price";f
cin>>price;        f
}
void show()
{
cout<<ano<<endl;
cout<<aname<<endl;
cout<<price<<endl;
getprice();
{
return price;
}
}
};
void main()
{
clrscr();
a.antique;
a.buy();
a.show();
getch();
}