nclude<iostream.h>
#include<conio.h>
#include<stdio.h>
struct()
{
char cntry[30];
char cap[30];
}
void main()
{
clrscr();
int ch;
char cntry[30];
char cap[30];
cout<<"\t\t\t\t (A) Enter your choice "<<endl;
cin>>ch;
cout<<"\t\t\t\t 1. name of the country "<<endl;
gets(cntry);
cout<<"\t\t\t\t 2. country's capital "<<endl;
gets(cap);
do
{
switch() ;
{
case 1:
cout<< "enter country name";
break;

case 2:
cout<< "enter capital name";
break;

case 3:
cout<< "enter another choice";
break;
while(ch!=0)
}
}
getch();
}

