#include<conio.h>
#include<iostream.h>
#include<stdio.h>
#include<string.h>
class person
{
char name(40);
int age;
public:
void Enter()
{
cout<<"Enter The Name Of The Space"<<endl;
gets(name);
cout<<"Enter The Age Of The Person"<<endl;
cin>>age;
}
v/oid Disp()
{
cout<<"Name Of The Person="<<name<<endl;
cout<<"Age Of The Person="<<age<<endl;
}
}p;
void Stdents()
{
int rollno;
int averagemarks;

p
.
.


