#include<iostream.h>
#include<conio.h>
void main()
{
	clrscr();
	int i,j,mat[3][3],sum1[3],sum2[3];
	cout<<"\n Enter 1 matrix :";
	for(i=0;i<3;i++)
	{
		for(j=0;j<3;j++)
		cin>>mat1[i][j];

	}
	cout<<"\n";
	cout<<"\n Entered matrix :";
	for(i=0;i<3;i++)
	{
		for(j=0;j<3;j++)
		cout<<mat1[i][j];
		cout<<"\t\n                 ";
	}
	cout<<"\n";
	for(i=0;i<3;i++)
	{
		for(j=0;j<3;j++)
		{
			sum1[i]=;
		}
	}
	cout<<"\n Sum of row :"<<sum1[i];
	getch();

}
