#include<iostream.h>
#include<conio.h>
void main()
{
int dd,yy,mm,valid=0, date;
cout<<"enter the date";
cin>>date;
{
if  (dd<=1dd>=31&& mm<=12&& yy<=0) ;
valid =0;
else
{
switch mm;
case 1:
case 3:
case 5:
case 7:
case 8:
case 10:
case 12:(dd=31);

break;
case 4:
case 6:
case 9:
case 11:(dd=30);

break;
case 2:(yy%4=0&& yy%100=0 && yy%400=0);

}     }
getch();
  }
